# Universidade Federal do Rio de Janeiro
# Escola Politecnica
# Departamento de Eletronica e de Computacao
# EEL270 - Computacao II - Turma 2021/2
# Prof. Marcelo Luiz Drumond Lanza
# Autor: Diego Rodrigues da Silva
# Descricao: makefile para o CentOS

# $Author: diego.silva $
# $Date: 2022/02/25 18:14:29 $
# $Log: GNUmakefile,v $
# Revision 1.55  2022/02/25 18:14:29  diego.silva
# *** empty log message ***
#
# Revision 1.54  2022/02/25 03:33:27  diego.silva
# *** empty log message ***
#
# Revision 1.53  2022/02/25 03:14:43  diego.silva
# *** empty log message ***
#
# Revision 1.52  2022/02/23 03:03:16  diego.silva
# *** empty log message ***
#
# Revision 1.51  2022/02/23 02:51:17  diego.silva
# *** empty log message ***
#
# Revision 1.50  2022/02/22 23:39:13  diego.silva
# *** empty log message ***
#
# Revision 1.49  2022/02/19 01:18:49  diego.silva
# *** empty log message ***
#
# Revision 1.48  2022/02/19 01:12:07  diego.silva
# *** empty log message ***
#
# Revision 1.47  2022/02/19 00:47:26  diego.silva
# *** empty log message ***
#
# Revision 1.46  2022/02/18 23:34:15  diego.silva
# *** empty log message ***
#
# Revision 1.45  2022/02/18 22:27:12  diego.silva
# *** empty log message ***
#
# Revision 1.44  2022/02/17 20:14:45  diego.silva
# *** empty log message ***
#
# Revision 1.43  2022/02/17 19:37:51  diego.silva
# *** empty log message ***
#
# Revision 1.42  2022/02/16 22:59:23  diego.silva
# *** empty log message ***
#
# Revision 1.41  2022/02/01 07:11:47  diego.silva
# *** empty log message ***
#
# Revision 1.40  2022/02/01 06:47:22  diego.silva
# *** empty log message ***
#
# Revision 1.39  2022/02/01 04:41:09  diego.silva
# *** empty log message ***
#
# Revision 1.38  2022/02/01 03:31:43  diego.silva
# *** empty log message ***
#
# Revision 1.37  2022/02/01 03:17:53  diego.silva
# *** empty log message ***
#
# Revision 1.36  2022/01/26 08:03:45  diego.silva
# *** empty log message ***
#
# Revision 1.35  2022/01/25 11:11:00  diego.silva
# *** empty log message ***
#
# Revision 1.34  2022/01/25 08:15:39  diego.silva
# *** empty log message ***
#
# Revision 1.33  2022/01/24 15:10:57  diego.silva
# *** empty log message ***
#
# Revision 1.32  2022/01/24 11:23:14  diego.silva
# *** empty log message ***
#
# Revision 1.31  2022/01/17 07:37:35  diego.silva
# *** empty log message ***
#
# Revision 1.30  2022/01/17 07:18:54  diego.silva
# *** empty log message ***
#
# Revision 1.29  2022/01/17 05:26:01  diego.silva
# *** empty log message ***
#
# Revision 1.28  2022/01/17 04:38:27  diego.silva
# *** empty log message ***
#
# Revision 1.27  2022/01/16 22:01:55  diego.silva
# *** empty log message ***
#
# Revision 1.26  2022/01/16 21:08:40  diego.silva
# *** empty log message ***
#
# Revision 1.25  2022/01/13 00:56:35  diego.silva
# *** empty log message ***
#
# Revision 1.24  2022/01/13 00:02:34  diego.silva
# *** empty log message ***
#
# Revision 1.23  2022/01/09 15:02:02  diego.silva
# *** empty log message ***
#
# Revision 1.22  2022/01/08 20:03:13  diego.silva
# *** empty log message ***
#
# Revision 1.21  2022/01/08 19:54:11  diego.silva
# *** empty log message ***
#
# Revision 1.20  2022/01/08 19:42:55  diego.silva
# *** empty log message ***
#
# Revision 1.19  2022/01/08 19:16:21  diego.silva
# *** empty log message ***
#
# Revision 1.18  2022/01/05 10:21:36  diego.silva
# *** empty log message ***
#
# Revision 1.17  2022/01/05 10:01:23  diego.silva
# *** empty log message ***
#
# Revision 1.16  2022/01/05 09:35:53  diego.silva
# *** empty log message ***
#
# Revision 1.15  2022/01/05 09:00:58  diego.silva
# *** empty log message ***
#
# Revision 1.14  2021/12/17 16:44:18  diego.silva
# *** empty log message ***
#
# Revision 1.13  2021/12/17 16:40:50  diego.silva
# *** empty log message ***
#
# Revision 1.12  2021/12/17 16:28:44  diego.silva
# *** empty log message ***
#
# Revision 1.11  2021/12/17 16:13:56  diego.silva
# *** empty log message ***
#
# Revision 1.10  2021/12/17 15:31:49  diego.silva
# *** empty log message ***
#
# Revision 1.9  2021/12/14 01:25:27  diego.silva
# *** empty log message ***
#
# Revision 1.8  2021/12/10 05:59:19  diego.silva
# *** empty log message ***
#
# Revision 1.7  2021/12/10 04:31:38  diego.silva
# *** empty log message ***
#
# Revision 1.6  2021/12/10 04:14:28  diego.silva
# *** empty log message ***
#
# Revision 1.5  2021/12/10 03:53:49  diego.silva
# *** empty log message ***
#
# Revision 1.4  2021/12/09 16:46:38  diego.silva
# *** empty log message ***
#
# Revision 1.3  2021/12/02 23:55:47  diego.silva
# *** empty log message ***
#
# Revision 1.2  2021/12/02 22:05:54  diego.silva
# *** empty log message ***
#
# Revision 1.1  2021/12/02 04:13:34  diego.silva
# Initial revision
#

OS = $(shell uname -s)

CC = gcc
AR = ar

ifeq ($(cc), CLANG)
CC = clang
endif

LD = $(CC)

DIALETO = ansi
STANDARD = -ansi

ifeq ($(dialeto), C89)
DIALETO = c89
STANDARD = -std=c89
endif

ifeq ($(dialeto), C90)
DIALETO = ansi
STANDARD = -std=c90
endif

ifeq ($(dialeto), C99)
DIALETO = c99
STANDARD = -std=c99
endif

ifeq ($(dialeto), C11)
DIALETO = c11
STANDARD = -std=c11
endif

ifeq ($(dialeto), C17)
DIALETO = c17
STANDARD = -std=c17
endif

CFLAGS = -Wall $(STANDARD)

LFLAGS = -Wall

AULA01 = aula0101\
		 aula0102\
		 aula0103

AULA02 = aula0202a\
		 aula0202b\
		 aula0202c\
		 aula0202d

AULA03 = aula0302a\
		 aula0302b\
		 aula0302c\
		 aula0302d

AULA04 = aula0402a\
		 aula0402b\
		 aula0402c\
		 aula0402d\
		 aula0404a\
		 aula0404b\
		 aula0404c\
		 aula0404d\
		 aula0404e

AULA05 = aula0502a\
		 aula0502b\
		 aula0503a\
		 aula0503b\
		 aula0505a\
		 aula0505b\
		 aula0506a\
		 aula0506b

AULA06 = aula0602\
		 aula0603\
		 aula0604\
		 aula0605\
		 aula0606

AULA07 = aula0702\
		 aula0703\
		 aula0704\
		 aula0705\
		 aula0706

AULA08 = aula0802\
		 aula0803\
		 aula0804\
		 aula0805\
		 aula0806\
		 aula0807\
		 aula0808\
		 aula0809

AULA09 = aula0902\
		 aula0903\
		 aula0904\
		 aula0905\
		 aula0906\
		 aula0907

AULA10 = aula10


AULA0101OBJS = aula0101.o
AULA0102OBJS = aula0102.o
AULA0103OBJS = aula0103.o

AULA0202AOBJS = aula0201a.o aula0202.o
AULA0202BOBJS = aula0201b.o aula0202.o
AULA0202COBJS = aula0201c.o aula0202.o
AULA0202DOBJS = aula0201d.o aula0202.o

AULA0302AOBJS = aula0301a.o aula0302.o
AULA0302BOBJS = aula0301b.o aula0302.o
AULA0302COBJS = aula0301c.o aula0302.o
AULA0302DOBJS = aula0301d.o aula0302.o

AULA0402AOBJS = aula0401a.o aula0402.o
AULA0402BOBJS = aula0401b.o aula0402.o
AULA0402COBJS = aula0401c.o aula0402.o
AULA0402DOBJS = aula0401d.o aula0402.o
AULA0404AOBJS = aula0403a.o aula0404.o
AULA0404BOBJS = aula0403b.o aula0404.o
AULA0404COBJS = aula0403c.o aula0404.o
AULA0404DOBJS = aula0403d.o aula0404.o
AULA0404EOBJS = aula0403e.o aula0404.o

AULA0502AOBJS = aula0501.o aula0502a.o
AULA0502BOBJS = aula0501.o aula0502b.o
AULA0503AOBJS = aula0501.o aula0503a.o
AULA0503BOBJS = aula0501.o aula0503b.o
AULA0505AOBJS = aula0504.o aula0505a.o
AULA0505BOBJS = aula0504.o aula0505b.o
AULA0506AOBJS = aula0504.o aula0506a.o
AULA0506BOBJS = aula0504.o aula0506b.o

AULA0602OBJS = aula0601.o aula0602.o
AULA0603OBJS = aula0601.o aula0603.o
AULA0604OBJS = aula0601.o aula0604.o
AULA0605OBJS = aula0601.o aula0605.o
AULA0606OBJS = aula0601.o aula0606.o

AULA0702OBJS = aula0701.o aula0702.o
AULA0703OBJS = aula0701.o aula0703.o
AULA0704OBJS = aula0701.o aula0704.o
AULA0705OBJS = aula0701.o aula0705.o
AULA0706OBJS = aula0701.o aula0706.o

AULA0802OBJS = aula0801.o aula0802.o
AULA0803OBJS = aula0801.o aula0803.o
AULA0804OBJS = aula0801.o aula0804.o
AULA0805OBJS = aula0801.o aula0805.o
AULA0806OBJS = aula0801.o aula0806.o
AULA0807OBJS = aula0801.o aula0807.o
AULA0808OBJS = aula0801.o aula0808.o
AULA0809OBJS = aula0801.o aula0809.o

AULA0902OBJS = aula0901.o aula0902.o
AULA0903OBJS = aula0901.o aula0903.o
AULA0904OBJS = aula0901.o aula0904.o
AULA0905OBJS = aula0901.o aula0905.o
AULA0906OBJS = aula0901.o aula0906.o
AULA0907OBJS = aula0901.o aula0907.o


LIBMATEMATICARECURSAOOBJS = aula0201a.o\
							aula0301a.o\
							aula0401a.o\
							aula0403a.o

LIBMATEMATICADOWHILEOBJS = aula0201b.o\
						   aula0301b.o\
						   aula0401b.o\
						   aula0403b.o

LIBMATEMATICAFOROBJS = aula0201c.o\
					   aula0301c.o\
					   aula0401c.o\
					   aula0403c.o

LIBMATEMATICAWHILEOBJS = aula0201d.o\
						 aula0301d.o\
						 aula0401d.o\
						 aula0403d.o

LIBMATEMATICAOBJS = aula0601.o

LIBMONITOROBJS = aula0701.o

LIBBASEOBJS = aula0801.o

LIBARQUIVOSOBJS = aula0901.o


LIBMATEMATICARECURSAO = libmatematicarecursao.a
LIBMATEMATICADOWHILE = libmatematicadowhile.a
LIBMATEMATICAFOR = libmatematicafor.a
LIBMATEMATICAWHILE = libmatematicawhile.a

LIBMATEMATICA = libmatematica.a

LIBMONITOR = libmonitor.a

LIBBASE = libbase.a

LIBARQUIVOS = libarquivos.a


EXECS = $(AULA01)\
		$(AULA02)\
		$(AULA03)\
		$(AULA04)\
		$(AULA05)\
		$(AULA06)\
		$(AULA07)\
		$(AULA08)\
		$(AULA09)\
		$(AULA10)

LIBS =	$(LIBMATEMATICARECURSAO)\
		$(LIBMATEMATICADOWHILE)\
		$(LIBMATEMATICAFOR)\
		$(LIBMATEMATICAWHILE)\
		$(LIBMATEMATICA)\
		$(LIBMONITOR)\
		$(LIBBASE)\
		$(LIBARQUIVOS)

ALL = $(EXECS) $(LIBS)

# Regra Implicita
.c.o:
	$(CC) $(CFLAGS) -c $<

all: $(ALL)

libmatematicarecursao.a: $(LIBMATEMATICARECURSAOOBJS)
	$(AR) -r -c $@ $^

libmatematicadowhile.a: $(LIBMATEMATICADOWHILEOBJS)
	$(AR) -r -c $@ $^

libmatematicafor.a: $(LIBMATEMATICAFOROBJS)
	$(AR) -r -c $@ $^

libmatematicawhile.a: $(LIBMATEMATICAWHILEOBJS)
	$(AR) -r -c $@ $^

libmatematica.a: $(LIBMATEMATICAOBJS)
	$(AR) -r -c $@ $^

libmonitor.a: $(LIBMONITOROBJS)
	$(AR) -r -c $@ $^

libbase.a: $(LIBBASEOBJS)
	$(AR) -r -c $@ $^

libarquivos.a: $(LIBARQUIVOSOBJS)
	$(AR) -r -c $@ $^


aula01: $(AULA01)
aula02: $(AULA02)
aula03: $(AULA03)
aula04: $(AULA04)
aula05: $(AULA05)
aula06: $(AULA06)
aula07: $(AULA07)
aula08: $(AULA08)
aula09: $(AULA09)
aula10: $(AULA10)

aula0101: $(AULA0101OBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0102: $(AULA0102OBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0103: $(AULA0103OBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)


aula0202a: $(AULA0202AOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0202b: $(AULA0202BOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0202c: $(AULA0202COBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0202d: $(AULA0202DOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)


aula0302a: $(AULA0302AOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0302b: $(AULA0302BOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0302c: $(AULA0302COBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0302d: $(AULA0302DOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)


aula0402a: $(AULA0402AOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0402b: $(AULA0402BOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0402c: $(AULA0402COBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0402d: $(AULA0402DOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0404a: $(LIBMATEMATICARECURSAO) $(AULA0404AOBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0404AOBJS) -L. -lmatematicarecursao
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0404b: $(LIBMATEMATICADOWHILE) $(AULA0404BOBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0404BOBJS) -L. -lmatematicadowhile
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0404c: $(LIBMATEMATICAFOR) $(AULA0404COBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0404COBJS) -L. -lmatematicafor
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0404d: $(LIBMATEMATICAWHILE) $(AULA0404DOBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0404DOBJS) -L. -lmatematicawhile
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0404e: $(AULA0404EOBJS)
	$(LD) $(LFLAGS) -o $@ $^ -L. -lm
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)


aula0502a: $(AULA0502AOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0502b: $(AULA0502BOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0503a: $(AULA0503AOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0503b: $(AULA0503BOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0505a: $(AULA0505AOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0505b: $(AULA0505BOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0506a: $(AULA0506AOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0506b: $(AULA0506BOBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)


aula0602: $(AULA0602OBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0603: $(AULA0603OBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0604: $(AULA0604OBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0605: $(AULA0605OBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0606: $(AULA0606OBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)


aula0702: $(AULA0702OBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0703: $(AULA0703OBJS)
	$(LD) $(LFLAGS) -o $@ $^
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0704: $(LIBMONITOR) $(AULA0704OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0704OBJS) -L. -lmonitor
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0705: $(LIBMONITOR) $(AULA0705OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0705OBJS) -L. -lmonitor
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0706: $(LIBMONITOR) $(AULA0706OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0706OBJS) -L. -lmonitor
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)


aula0802: $(LIBBASE) $(AULA0802OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0802OBJS) -L. -lbase
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0803: $(LIBBASE) $(AULA0803OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0803OBJS) -L. -lbase
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0804: $(LIBBASE) $(AULA0804OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0804OBJS) -L. -lbase
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0805: $(LIBBASE) $(AULA0805OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0805OBJS) -L. -lbase
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0806: $(LIBBASE) $(AULA0806OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0806OBJS) -L. -lbase
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0807: $(LIBBASE) $(AULA0807OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0807OBJS) -L. -lbase
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0808: $(LIBBASE) $(AULA0808OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0808OBJS) -L. -lbase
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0809: $(LIBBASE) $(AULA0809OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0809OBJS) -L. -lbase
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)


aula0902: $(LIBARQUIVOS) $(AULA0902OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0902OBJS) -L. -larquivos
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0903: $(LIBARQUIVOS) $(AULA0903OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0903OBJS) -L. -larquivos
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0904: $(LIBARQUIVOS) $(AULA0904OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0904OBJS) -L. -larquivos
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0905: $(LIBARQUIVOS) $(AULA0905OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0905OBJS) -L. -larquivos
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0906: $(LIBARQUIVOS) $(AULA0906OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0906OBJS) -L. -larquivos
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

aula0907: $(LIBARQUIVOS) $(AULA0907OBJS)
	$(LD) $(LFLAGS) -o $@ $(AULA0907OBJS) -L. -larquivos
	cp $@ $@-$(OS)-$(CC)-$(DIALETO)

 
.PHONY: clean-all clean clean-objs clean-freebsd clean-linux clean-gcc clean-clang clean-ansi clean-c89 clean-c99 clean-c11

clean:
	rm -f *.o $(ALL) *.core

clean-all:
	rm -f *.o $(ALL) *-FreeBSD-* *-Linux-* *.core

clean-objs:
	rm -f *.o *.core

clean-freebsd:
	rm -f *.o $(ALL) *-FreeBSD-* *.core

clean-linux:
	rm -f *.o $(ALL) *-Linux-* *.core

clean-gcc:
	rm -f *.o $(ALL) *-gcc-* *.core

clean-clang:
	rm -f *.o $(ALL) *-clang-* *.core

clean-ansi:
	rm -f *.o $(ALL) *-ansi *.core

clean-c89:
	rm -f *.o $(ALL) *-c89 *.core

clean-c99:
	rm -f *.o $(ALL) *-c99 *.core

clean-c11:
	rm -f *.o $(ALL) *-c11 *.core
 
# $RCSfile: GNUmakefile,v $
